### ISSUE TITLE
Usage of sourcemaps

### ISSUE THREAD

**Issue by dewdad** [steelbrain/denode#15]
I have a pretty common configuration.
/src    -- ES6/7 js files
/build -- ES5 transpiled sources with source maps

How would I debug scripts from the "src" directory with Denode?

Thank you,
Avital

**Comment by steelbrain** [comment]
#### If your build files don't have source maps

You need to configure your transpiler to either inline source maps (not recommended) or create soruce maps and put them with the files.

If you're using babel, this command works

```
babel src --out-dir build --presets es2015 --source-maps
```

#### If your build files already have source maps

Check if each file has `@sourceMappingURL` at the end, if it does, it'll work. Otherwise, tell your transpiler to add it :)

Let me know how it goes

**Comment by dewdad** [comment]
What would the debugger command look like? Would it be issued with the
source in the build?

**Comment by steelbrain** [comment]
There's no debugger command, if your files have source maps, you'll be shown the source files at their paths in the `Sources` tab of chromium dev tools :)

**Comment by dewdad** [comment]
This is Node application, there is no URL (@sourceMappingURL) if I'm not
mistaken.

**Comment by steelbrain** [comment]
I understand that it's a Node application, but we actually chromium dev tools need that sourceMappingURL to support source maps, otherwise they wouldn't know where are they are located.

Another thing to note here is that not only chromium, but any spec compliant source map support package for Node.js also requires this. So you will _have_ to include that (most transpilers do this automatically if you tell them to generate source maps) for source maps to work
